apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: github-copilot-playground
  title: GitHub Copilot Playground
  description: A GitHub Copilot Playground for testing out GitHub Copilot
  tags:
    - ai
spec:
  type: library
  lifecycle: experimental
  owner: johnnyhuy